### ISSUE TITLE
Basic Aithentication not working with Mule server 3.8.0

### ISSUE THREAD

**Issue by Vinay-Samudre** [http-builder-ng/http-builder-ng#150] opened 2017-07-18 00:03 UTC
`**build.gradle**:
group 'org.vinay.rest'
version '1.0-SNAPSHOT'

apply plugin: 'groovy'
apply plugin: 'java'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    // https://mvnrepository.com/artifact/io.github.http-builder-ng/http-builder-ng-core
    testRuntime group: 'io.github.http-builder-ng', name: 'http-builder-ng-core', version: '0.17.0'
//    testRuntime group: 'io.github.http-builder-ng', name: 'http-builder-ng-core', version: '0.16.0'
    testCompile group: 'junit', name: 'junit', version: '4.12'
    testCompile group: 'org.spockframework', name: 'spock-core', version: '1.0-groovy-2.4'
    testCompile group: 'ch.qos.logback', name: 'logback-classic', version:'1.0.13'
}
`

`**GetD2LBySourcedIdSpec.groovy**:
import spock.lang.Shared
import spock.lang.Specification
import groovyx.net.http.HttpBuilder

/**
 * Created by e5017581 on 11/07/2017.
 */
class GetD2LUserBySourcedIdSpec  extends Specification {
   def "test get /users call with d2lSourced Id"() {
       given:

       def httpClient = HttpBuilder.configure {
           request.uri = 'http://esbvucmv5.vu.edu.au'
           //request.headers['Authorization'] = 'Basic ZDJscnM6MTRkMmxycw=='
           //request.headers['Content-Type'] = "application/json"
           request.auth.basic'd2lrs', '14d2lrs'
       }

       when:
       def user = httpClient.get {
           //request.auth.basic 'd2lrs', '14d2lrs'
          // request.headers['Authorization'] = 'Basic ZDJscnM6MTRkMmxycw=='
           request.uri.path = '/D2L/2.0/users/'
           request.uri.query = [sourcedId: 's4504565']
       }
       then:
       println user.dump()
       null != user
   }
}
`
`**Client logs**:
"C:\Program Files\Java\jdk1.8.0_121\bin\java" -ea -Didea.test.cyclic.buffer.size=1048576 "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.1.5\lib\idea_rt.jar=58014:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.1.5\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.1.5\lib\idea_rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.1.5\plugins\junit\lib\junit-rt.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\rt.jar;C:\Users\e5017581\IdeaProjects\http-builder-ng2\build\classes\test;C:\Users\e5017581\IdeaProjects\http-builder-ng2\build\resources\test;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\junit\junit\4.12\2973d150c0dc1fefe998f834810d68f278ea58ec\junit-4.12.jar;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\org.spockframework\spock-core\1.0-groovy-2.4\ceaa8b69f274ed3de24da3e6a6c86f673b426d1a\spock-core-1.0-groovy-2.4.jar;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\ch.qos.logback\logback-classic\1.0.13\6b56ec752b42ccfa1415c0361fb54b1ed7ca3db6\logback-classic-1.0.13.jar;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\org.hamcrest\hamcrest-core\1.3\42a25dc3219429f0e5d060061f71acb49bf010a0\hamcrest-core-1.3.jar;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\org.codehaus.groovy\groovy-all\2.4.1\a9ca9c9de09361ec2a18d2c058d2524fbd8eae0c\groovy-all-2.4.1.jar;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\io.github.http-builder-ng\http-builder-ng-core\0.17.0\b2322bff1f06f58699b6221fbf683bdec382cb74\http-builder-ng-core-0.17.0.jar;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\ch.qos.logback\logback-core\1.0.13\dc6e6ce937347bd4d990fc89f4ceb469db53e45e\logback-core-1.0.13.jar;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\org.slf4j\slf4j-api\1.7.5\6b262da268f8ad9eff941b25503a9198f0a0ac93\slf4j-api-1.7.5.jar;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\xml-resolver\xml-resolver\1.2\3d0f97750b3a03e0971831566067754ba4bfd68c\xml-resolver-1.2.jar;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\org.slf4j\slf4j-api\1.7.21\139535a69a4239db087de9bab0bee568bf8e0b70\slf4j-api-1.7.21.jar" com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 "GetD2LUserBySourcedIdSpec,test get /users call with d2lSourced Id"
09:59:45,792 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.groovy] at [file:/C:/Users/e5017581/IdeaProjects/http-builder-ng2/build/resources/test/logback.groovy]
09:59:46,108 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@6d07a63d - Added status listener of type [ch.qos.logback.core.status.OnConsoleStatusListener]
09:59:46,123 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@6d07a63d - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
09:59:46,125 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@6d07a63d - Naming appender as [CONSOLE]
09:59:46.460 [main] DEBUG g.net.http.JavaHttpBuilder.headers - Request-Header: Accept-Encoding -> [gzip, deflate]
09:59:46.818 [main] DEBUG g.net.http.JavaHttpBuilder.content - Response-Body: null
09:59:46.818 [main] DEBUG g.net.http.JavaHttpBuilder.headers - Response-Header: Date -> Mon, 17 Jul 2017 23:59:46 GMT
09:59:46.818 [main] DEBUG g.net.http.JavaHttpBuilder.headers - Response-Header: Content-Type -> text/plain
09:59:46.818 [main] DEBUG g.net.http.JavaHttpBuilder.headers - Response-Header: Content-Length -> 42
09:59:46.818 [main] DEBUG g.net.http.JavaHttpBuilder.headers - Response-Header: Connection -> keep-alive
09:59:46.818 [main] DEBUG g.net.http.JavaHttpBuilder.headers - Response-Header: Server -> Mule/SNAPSHOT
09:59:46.818 [main] DEBUG g.net.http.JavaHttpBuilder.headers - Response-Header: WWW-Authenticate -> Basic realm="realm"
09:59:46.818 [main] DEBUG g.net.http.JavaHttpBuilder.headers - Response-Header: http.status -> 401
09:59:46.819 [main] DEBUG g.net.http.JavaHttpBuilder.headers - Response-Header: Set-Cookie -> VUpersist=rd2480o00000000000000000000ffff0a4c003do80; path=/; Httponly

groovyx.net.http.HttpException: Unauthorized

	at groovyx.net.http.NativeHandlers.failure(NativeHandlers.java:69)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovyx.net.http.fn.ClosureBiFunction.apply(ClosureBiFunction.java:45)
	at groovyx.net.http.HttpBuilder$ResponseHandlerFunction.apply(HttpBuilder.java:1834)
	at groovyx.net.http.JavaHttpBuilder$Action.lambda$execute$2(JavaHttpBuilder.java:157)
	at groovyx.net.http.JavaHttpBuilder$ThreadLocalAuth.with(JavaHttpBuilder.java:320)
	at groovyx.net.http.JavaHttpBuilder$Action.execute(JavaHttpBuilder.java:111)
	at groovyx.net.http.JavaHttpBuilder.createAndExecute(JavaHttpBuilder.java:362)
	at groovyx.net.http.JavaHttpBuilder.doGet(JavaHttpBuilder.java:369)
	at groovyx.net.http.HttpObjectConfigImpl.nullInterceptor(HttpObjectConfigImpl.java:45)
	at groovyx.net.http.HttpBuilder.get(HttpBuilder.java:360)
	at groovyx.net.http.HttpBuilder.get(HttpBuilder.java:1311)
	at GetD2LUserBySourcedIdSpec.test get /users call with d2lSourced Id(GetD2LUserBySourcedIdSpec.groovy:20)

Process finished with exit code -1
`
**Couldn't find any logs in server**

As you can see in client logs its not sending client Authentication header.

**Comment by cjstehno** [comment] 2017-07-18 02:00
Since this works fine on Tomcat and Undertow, I'd guess this is a problem related to the specific server. You may want to try the Apache or OkHttp implementation to see if you have the same issue.

**Comment by cjstehno** [comment] 2017-07-18 02:02
Also, is the server in your test publicly available for us to test against? If not please provide a standalone example.

**Comment by Vinay-Samudre** [comment] 2017-07-18 05:52
I just tried Apache, its still not working, please logs below:

`"C:\Program Files\Java\jdk1.8.0_121\bin\java" -ea -Didea.test.cyclic.buffer.size=1048576 "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.1.5\lib\idea_rt.jar=57076:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.1.5\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.1.5\lib\idea_rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.1.5\plugins\junit\lib\junit-rt.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\rt.jar;C:\Users\e5017581\IdeaProjects\http-builder-ng2\build\classes\test;C:\Users\e5017581\IdeaProjects\http-builder-ng2\build\resources\test;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\junit\junit\4.12\2973d150c0dc1fefe998f834810d68f278ea58ec\junit-4.12.jar;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\org.spockframework\spock-core\1.0-groovy-2.4\ceaa8b69f274ed3de24da3e6a6c86f673b426d1a\spock-core-1.0-groovy-2.4.jar;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\ch.qos.logback\logback-classic\1.0.13\6b56ec752b42ccfa1415c0361fb54b1ed7ca3db6\logback-classic-1.0.13.jar;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\org.hamcrest\hamcrest-core\1.3\42a25dc3219429f0e5d060061f71acb49bf010a0\hamcrest-core-1.3.jar;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\org.codehaus.groovy\groovy-all\2.4.1\a9ca9c9de09361ec2a18d2c058d2524fbd8eae0c\groovy-all-2.4.1.jar;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\io.github.http-builder-ng\http-builder-ng-apache\0.17.0\8da7abc862667acee105446f02cc47f62e549019\http-builder-ng-apache-0.17.0.jar;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\ch.qos.logback\logback-core\1.0.13\dc6e6ce937347bd4d990fc89f4ceb469db53e45e\logback-core-1.0.13.jar;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\org.slf4j\slf4j-api\1.7.5\6b262da268f8ad9eff941b25503a9198f0a0ac93\slf4j-api-1.7.5.jar;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\io.github.http-builder-ng\http-builder-ng-core\0.17.0\b2322bff1f06f58699b6221fbf683bdec382cb74\http-builder-ng-core-0.17.0.jar;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\org.apache.httpcomponents\httpclient\4.5.2\733db77aa8d9b2d68015189df76ab06304406e50\httpclient-4.5.2.jar;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\org.apache.httpcomponents\httpmime\4.5.2\22b4c53dd9b6761024258de8f9240c3dce6ea368\httpmime-4.5.2.jar;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\xml-resolver\xml-resolver\1.2\3d0f97750b3a03e0971831566067754ba4bfd68c\xml-resolver-1.2.jar;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\org.apache.httpcomponents\httpcore\4.4.4\b31526a230871fbe285fbcbe2813f9c0839ae9b0\httpcore-4.4.4.jar;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\commons-logging\commons-logging\1.2\4bfc12adfe4842bf07b657f0369c4cb522955686\commons-logging-1.2.jar;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\commons-codec\commons-codec\1.9\9ce04e34240f674bc72680f8b843b1457383161a\commons-codec-1.9.jar;C:\Users\e5017581\.gradle\caches\modules-2\files-2.1\org.slf4j\slf4j-api\1.7.21\139535a69a4239db087de9bab0bee568bf8e0b70\slf4j-api-1.7.21.jar" com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 "GetD2LUserBySourcedIdSpec,test get /users call with d2lSourced Id"
15:51:16,668 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.groovy] at [file:/C:/Users/e5017581/IdeaProjects/http-builder-ng2/build/resources/test/logback.groovy]
15:51:16,971 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@6e005dc9 - Added status listener of type [ch.qos.logback.core.status.OnConsoleStatusListener]
15:51:16,986 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@6e005dc9 - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
15:51:16,988 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@6e005dc9 - Naming appender as [CONSOLE]
15:51:17.199 [main] DEBUG g.net.http.JavaHttpBuilder.headers - Request-Header: Accept-Encoding -> [gzip, deflate]
15:51:17.433 [main] DEBUG g.net.http.JavaHttpBuilder.content - Response-Body: null
15:51:17.433 [main] DEBUG g.net.http.JavaHttpBuilder.headers - Response-Header: Date -> Tue, 18 Jul 2017 05:51:17 GMT
15:51:17.433 [main] DEBUG g.net.http.JavaHttpBuilder.headers - Response-Header: Content-Type -> text/plain
15:51:17.433 [main] DEBUG g.net.http.JavaHttpBuilder.headers - Response-Header: Content-Length -> 42
15:51:17.433 [main] DEBUG g.net.http.JavaHttpBuilder.headers - Response-Header: Connection -> keep-alive
15:51:17.433 [main] DEBUG g.net.http.JavaHttpBuilder.headers - Response-Header: Server -> Mule/SNAPSHOT
15:51:17.433 [main] DEBUG g.net.http.JavaHttpBuilder.headers - Response-Header: WWW-Authenticate -> Basic realm="realm"
15:51:17.433 [main] DEBUG g.net.http.JavaHttpBuilder.headers - Response-Header: http.status -> 401
15:51:17.433 [main] DEBUG g.net.http.JavaHttpBuilder.headers - Response-Header: Set-Cookie -> VUpersist=rd2480o00000000000000000000ffff0a4c003do80; path=/; Httponly

groovyx.net.http.HttpException: Unauthorized

	at groovyx.net.http.NativeHandlers.failure(NativeHandlers.java:69)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovyx.net.http.fn.ClosureBiFunction.apply(ClosureBiFunction.java:45)
	at groovyx.net.http.HttpBuilder$ResponseHandlerFunction.apply(HttpBuilder.java:1834)
	at groovyx.net.http.JavaHttpBuilder$Action.lambda$execute$2(JavaHttpBuilder.java:157)
	at groovyx.net.http.JavaHttpBuilder$ThreadLocalAuth.with(JavaHttpBuilder.java:320)
	at groovyx.net.http.JavaHttpBuilder$Action.execute(JavaHttpBuilder.java:111)
	at groovyx.net.http.JavaHttpBuilder.createAndExecute(JavaHttpBuilder.java:362)
	at groovyx.net.http.JavaHttpBuilder.doGet(JavaHttpBuilder.java:369)
	at groovyx.net.http.HttpObjectConfigImpl.nullInterceptor(HttpObjectConfigImpl.java:45)
	at groovyx.net.http.HttpBuilder.get(HttpBuilder.java:360)
	at groovyx.net.http.HttpBuilder.get(HttpBuilder.java:1311)
	at GetD2LUserBySourcedIdSpec.test get /users call with d2lSourced Id(GetD2LUserBySourcedIdSpec.groovy:20)


Process finished with exit code -1
`

**Comment by cjstehno** [comment] 2017-07-18 09:54
Please provide a standalone means if reproducing this issue. The server URL specified does not seem to be public and from what I see, mule is a commercial product.

**Comment by aaronhagopian** [comment] 2017-07-18 19:30
I did a simple server with ratpack and used curl and your library as a test.  Sorry if this is a bit sloppy, used this opportunity to try out ratpack since I have not used it before.

**server.groovy**
```groovy
@Grapes([
  @Grab('io.ratpack:ratpack-groovy:1.5.0-rc-2'),
  @Grab('org.slf4j:slf4j-simple:1.7.25'),
])
import static ratpack.groovy.Groovy.ratpack
import java.util.logging.Logger
Logger log = Logger.getLogger("")

ratpack {
    handlers {
        get {
			request.headers?.names?.each { name -> log.info "HEADER: ${name}, VALUES: ${request.headers?.getAll(name)}"} 
			if(request.headers?.names?.find{ it =~ /Authorization/ }) {
				render "found an attempt at authorization"
			} else {
				render "no attempt at authorization"
			}
        }

    }
}
```

**client.groovy**
```groovy
@Grab('io.github.http-builder-ng:http-builder-ng-apache:0.17.0')

def response = groovyx.net.http.HttpBuilder.configure {
    request.uri = 'http://localhost:5050'
}.get {
    request.auth.basic 'user', 'p4ss'
    request.uri.path = '/'}
	
println response

```
launch the server in a separate console:
```bash
$ groovy server
[main] INFO ratpack.server.RatpackServer - Starting server...
[main] INFO ratpack.server.RatpackServer - Building registry...
[main] INFO ratpack.server.RatpackServer - Ratpack started (development) for http://localhost:5050
...
```

With the server running, using curl on linux I get:
```bash
$ curl -u user:p4ss http://localhost:5050/ 
found an attempt at authorization
```

Using my groovy script client I get:
```groovy
$ groovy client
no attempt at authorization
```

And you can see on the server output that no header with "Authorization" comes when using the http-buildler-ng client.

**Comment by cjstehno** [comment] 2017-07-18 19:47
Interesting. There is no actual security configuration in your example. If it's purely a matter of missing that header, I would think this problem would appear in any server. I think there is more to this issue. If I get some time soon, I will give your example a try with an actual BASIC handler in place (pac4j or something).

Thanks for the code example.

**Comment by aaronhagopian** [comment] 2017-07-18 21:49
Ok I took a minute to understand basic auth since while I get what it is, I didn't realize there was a bit more to the flow of it.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication

I emulated the flow described in the link above in my ratpack example and the client worked as expected so @Vinay-Samudre  you may want to take a closer look at the interaction with your Mule Server.  It looks like this client follows the expection of the server to response with the supported authentication, even though you have provided to it basic auth, it won't try without that initial 401.

see my new server example
**server.groovy**
```groovy
@Grapes([
  @Grab('io.ratpack:ratpack-groovy:1.5.0-rc-2'),
  @Grab('org.slf4j:slf4j-simple:1.7.25'),
])
import static ratpack.groovy.Groovy.ratpack
import ratpack.http.internal.*
import io.netty.handler.codec.http.HttpResponseStatus
import java.util.logging.Logger
Logger log = Logger.getLogger("")

ratpack {
    handlers {
        get {
			request.headers?.names?.each { name -> log.info "HEADER: ${name}, VALUES: ${request.headers?.getAll(name)}"} 
			if(request.headers?.names?.find{ it =~ /Authorization/ }) {
				render "found an attempt at authorization"
			} else {
				response.status = new DefaultStatus(HttpResponseStatus.UNAUTHORIZED)
				response.headers.add('WWW-Authenticate', 'Basic realm="Access to the site requires auth"')
				render "no attempt at authorization"
			}
        }
    }
}
```

Now my same client.groovy example works.

**Comment by Vinay-Samudre** [comment] 2017-07-19 00:33
@aaronhagopian as you can see my client logs I am getting 401.

Also I modified your  client.groovy script and tried with MULE server but I am getting "java.lang.RuntimeException: java.net.ProtocolException: Server redirected too many  times (20)"

client.groovy:
`@Grab('io.github.http-builder-ng:http-builder-ng-apache:0.17.0')

def response = groovyx.net.http.HttpBuilder.configure {
    request.uri = 'http://esbvucmv5.vu.edu.au'
    request.cookie('user-id', 'some-identifier')
}.get {
    request.auth.basic 'd2lrs', '14d2lrs'
    request.uri.path = '/D2L/2.0/users/'}

println response
`

**Comment by cjstehno** [comment] 2017-07-19 01:16
You may want to contact your support with mule or their docs to see if there are any differences in how they support basic authentication.

**Comment by Vinay-Samudre** [comment] 2017-07-19 01:24
I can confirm that with old http-builder it used to work.

**Comment by cjstehno** [comment] 2017-07-19 14:53
Our version of the Apache client is newer than that used by the legacy HttpBuilder. There may be some incompatibility between the current Apache client and the web server exposed by Mule.

The authorization configuration we use is simply delegated to the underlying client. You might try using the Apache HttpComponents client directly to see if you can get that working. If it works, you could provide the working example and we can see what's different from what we have internally.

I plan on trying out a Ratpack implementation with full basic auth support later this week, but without the ability to use the server you are using, we can't do much more than show it working on a bunch of other servers, which seems to point to Mule doing something non-standard or at least different.

**Comment by cjstehno** [comment] 2017-07-19 18:56
Actually, @aaronhagopian your last example is good enough for a real basic authentication implementation on ratpack - I found a blog post that had pretty much the same configuration.

**Comment by harshajith** [comment] 2017-08-17 02:47
I faced the same issue but managed to get it to work after setting a header with basic auth string.

    request.headers['Authorization'] = encodedAuthString 
(i.e :  encodedString is something similar to "username:password".bytes.encodeBase64().toString()

**Comment by cjstehno** [comment] 2017-08-17 12:16
Yes, that's what is actually done by the HTTP clients underneath, but there is a handshake operation that the mule server seems to omit. This seems to be an issue with either the mule server or the underlying clients. The work-around being what was stated above.

If examples of this working correctly without work-around can be provided with one of our underlying clients we can address it as an issue on our side, but until then I am going to close this issue.

**Closed by cjstehno** 2017-08-17 12:16 UTC
Labels: wontfix
